### ISSUE TITLE
Train error need help!

### ISSUE THREAD

**Issue by m-wei** [jaredleekatzman/DeepSurv#11]
I don't get my own data,so I make a data,like:  dataset = {'x':np.array([[0.1,0.3],[0.4,0.5],[0.3,0.2],[0.8,0.7],[0.5,0.2]],dtype = np.float32),'e':np.array([0,1,1,0,1],dtype = np.int32),'t':np.array([0.2,0.3,0.4,0.8,0.9],dtype = np.float32)}

### please tell me whether the data is right?
can you give me a file about the data??

my train code:

import deepsurv
import pandas as pd
import numpy as np
#dataset = pd.read_csv('/home/mw/mw/work/DeepSurv-master/test.csv')
dataset = {'x':np.array([[0.1,0.3],[0.4,0.5],[0.3,0.2],[0.8,0.7],[0.5,0.2]],dtype = np.float32),'e':np.array([0,1,1,0,1],dtype = np.int32),'t':np.array([0.2,0.3,0.4,0.8,0.9],dtype = np.float32)}
train_data = dataset
valid_data = dataset
network = deepsurv.DeepSurv(n_in =2,learning_rate = 1e-5)
log = network.train(train_data, valid_data, n_epochs=500)

### Again,when I train the network I meet a problem:

Traceback (most recent call last):
  File "test.py", line 14, in <module>
    log = network.train(train_data, valid_data, n_epochs=500,logger = None)
  File "/home/mw/mw/work/DeepSurv-master/deepsurv/deep_surv.py", line 397, in train
    update_fn = update_fn, **kwargs
  File "/home/mw/mw/work/DeepSurv-master/deepsurv/deep_surv.py", line 242, in _get_train_valid_fn
    learning_rate=learning_rate, **kwargs
  File "/home/mw/mw/work/DeepSurv-master/deepsurv/deep_surv.py", line 208, in _get_loss_updates
    if self.restored_update_params:
AttributeError: DeepSurv instance has no attribute 'restored_update_params'
[here](https://github.com/jaredleekatzman/DeepSurv/blob/master/deepsurv/deep_surv.py#L208)
 
### so I comment the code,but another question happens:
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    log = network.train(train_data, valid_data, n_epochs=500,logger = None)
  File "/home/mw/mw/work/DeepSurv-master/deepsurv/deep_surv.py", line 410, in train
    logger.logValue('loss', loss, epoch)
AttributeError: 'NoneType' object has no attribute 'logValue'

I don't know whether the cause of my data or other question,Please give me some help ! Thank you very much first !

**Comment by dareneiri** [comment]
It's not your data causing problems. I think you're using the deepsurv version from the master branch, which is not reflective of the documentation currently available. 

I recommend uninstalling the current version you have now and reinstalling with pip. https://pypi.python.org/pypi/deepsurv/0.1.0.  You will not get the errors you are getting with the older version.

If you decide to use the latest version, which you are currently using, then follow what I wrote in https://github.com/jaredleekatzman/DeepSurv/issues/7 . There are new features that he added that aren't fully documented yet; it's not an official release. 

I recommend reading @jaredleekatzman's paper on deepsurv. There he notes he used breast cancer survival data, which is available online and you can use that as your test data until you have your own data prepared.

**Comment by m-wei** [comment]
Great! thank you very much!!!

**Comment by m-wei** [comment]
Great! thank you very much again!

**Comment by jaredleekatzman** [comment]
@m-wei I'm sorry that the package broke while I was updating and making modifications to the repo. I've released an updated version of DeepSurv. Let me know if the same problems persists.
