### ISSUE TITLE
Thank you for the package

### ISSUE THREAD

**Issue by scienceaiden** [jaredleekatzman/DeepSurv#17]
Would love to see your examples. and could not find py.test - was it part of the package?
your base module for windows does not have it

All the best!

**Comment by scienceaiden** [comment]
it seems like your package does not work even with your own example. it's pity

**Comment by dareneiri** [comment]
@scienceaiden. I have been able to use this package without any issue. I admit the documentation can be improved, but I've used publicly available survival datasets and get CI's greater than 0.6. I've commented on previous issues where I document how I've been able to use DeepSurv. Keep in mind that if you get deepsurv from PyPi (pip) then you'll be getting an older version than what's available from the master branch.

**Comment by scienceaiden** [comment]
@dareneiri I have been trying to download using pip or running directly from source code to no avails. and why do you think 0.6 is good result? theano proven to have much higher results

**Comment by dareneiri** [comment]
@scienceaiden My point regarding getting a CI >0.6 was that DeepSurv works. For datasets I'm working with I usually get 0.8-0.9. 

Can't say I understand why you're getting the same code from pip or from github. They're different for me. If I download from https://pypi.python.org/pypi/deepsurv/0.1.0 and check the files there, the source code is completely different from what's available here. 

If you provide specific details about how you're trying to install and get DeepSurv to work, then I can try to help (I am not involved with DeepSurv directly, just very familiar with it).

**Comment by scienceaiden** [comment]
@dareneiri thank you for the help.

you are right - if i compare master ( in https://github.com/jaredleekatzman/DeepSurv) with deepsurv (in anaconda  site-packages) folder, they are different.
what i meant is that i take all those class methods and definition and embed in the code and run, it gave me all sort of errors starting with different shape, etc. etc. 

please guide me how can i install from the master properly.

**Comment by scienceaiden** [comment]
@dareneiri  thanks for the awesome writeup

i did like you said and when i import, i have this error message about lazylinker_ext.pyd Access is denied.

have you had experienced before?

**Comment by dareneiri** [comment]
Looks like it might be related to Windows updates? 
https://github.com/Theano/Theano/issues/2733

But I can't say for sure as I haven't had that issue; I installed theano on a linux system.

**Comment by scienceaiden** [comment]
@dareneiri  thank you - you helped enough

btw: cannot get access to DeepSurv.git now...

**Comment by dareneiri** [comment]
what is specific error?

**Comment by scienceaiden** [comment]
@dareneiri  access denied

**Comment by dareneiri** [comment]
I don't have a problem running this on my system: 
`pip install git+https://github.com/jaredleekatzman/DeepSurv.git`
This is likely coming from your own system and its own permission settings for your directory.

**Comment by scienceaiden** [comment]
@dareneiri ok, i will try to reboot router just in case as well.

thank you for all your help

**Comment by scienceaiden** [comment]
@dareneiri , after reinstalling everything from scratch, it works. thank you

**Comment by arturomoncadatorres** [comment]
As of today, I managed to install `DeepSurv` in a Windows 10 machine, 64 bit, running Python 3.7 and Anaconda using [dareneiri instructions](https://github.com/jaredleekatzman/DeepSurv/issues/17#issuecomment-334852574). However, I still needed to install [`h5py`](https://pypi.org/project/h5py/). For the sake of completion, this is what worked for me:

```
pip install --upgrade https://github.com/Theano/Theano/archive/master.zip
pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
pip install git+https://github.com/jaredleekatzman/DeepSurv.git
pip install h5py
```
