### ISSUE TITLE
viz.py plotting error

### ISSUE THREAD

**Issue by scienceML** [jaredleekatzman/DeepSurv#18]
Hello,

When i use vix.py to plot log in the code below, I get next error

`deepsurv.plot_log(log)
network.get_concordance_index(**atest)
`

`File "C:\...\deepsurv\viz.py", line 38, in plot_log
    num_epochs = len(log[TRAIN_LOSS])
KeyError: 'loss'

network.get_concordance_index(**atest)
Out[38]: 0.65957446808510634
`

Any idea where this key error comes from ?

**Comment by jaredleekatzman** [comment]
@scienceML you were probably running an incomplete version of DeepSurv. The key `'loss'`is used used by the logger to maintain the log-likelihood loss during training. Old versions used to use the key 'train'.
I've updated master to include a new version. Let me know if you are still receiving this error

**Comment by scienceML** [comment]
@jaredleekatzman  I do have the latest version, compared the code with currently available in master .
just added some fixes from issue# 7 to save and load  functions. i'll try to reinstall and run again.

**Comment by scienceML** [comment]
@jaredleekatzman , all good- thank you
