### ISSUE TITLE
AttributeError for deepsurv

### ISSUE THREAD

**Issue by coranholmes** [jaredleekatzman/DeepSurv#29]
I am a newbie for survival analysis. I try to set up the docker and run the experiments (linear) and have got the following error
```
deepsurv_1  | ('Saving model parameters to output file', '/shared/results/modelslinear_model_selu_0.jsone7d7f147-c66a-4478-9375-171ba5c13379.h5')
deepsurv_1  | Traceback (most recent call last):
deepsurv_1  |   File "/scripts/deepsurv_run.py", line 165, in <module>
deepsurv_1  |     save_model(model, output_file)
deepsurv_1  |   File "/scripts/deepsurv_run.py", line 100, in save_model
deepsurv_1  |     model.save_weights(output_file)
deepsurv_1  | AttributeError: 'str' object has no attribute 'save_weights'
```
So what shall I do with this error?

**Comment by jaredleekatzman** [comment]
@coranholmes 
Ah that's an error I found and fixed in the `revision`branch of DeepSurv. 
I just merged the bug fix into `master`. Let me know if the problem persists, or if other bugs come up

**Comment by coranholmes** [comment]
@jaredleekatzman hi, currently the error doesn't appear. But I have got another issue. Please see issue #31

**Comment by otuns** [comment]
I am still having this error please

hp_search_1  | Saving model parameters to output file /logs/modelsnewdat_model_selu_0.json95c19ae5-da1b-4a76-9ef2-965222ceb869.h5
hp_search_1  | Traceback (most recent call last):
hp_search_1  |   File "/deepsurv_run.py", line 165, in <module>
hp_search_1  |     save_model(model, output_file)
hp_search_1  |   File "/deepsurv_run.py", line 100, in save_model
hp_search_1  |     model.save_weights(output_file)
hp_search_1  | AttributeError: 'str' object has no attribute 'save_weights'
deepsurv_hp_search_1 exited with code 1
