### ISSUE TITLE
[Request] Example from your paper

### ISSUE THREAD

**Issue by alexhallam** [jaredleekatzman/DeepSurv#4]
Great module! 

Do you have code that runs through the same simulation that you described in your paper?

**Comment by abracadabrac** [comment]
yes I would love it too

**Comment by jaredleekatzman** [comment]
Thank you for the comments! 
I am currently working on refactoring and publishing that code to help researchers start implementing their own experiments

**Comment by jlkravitz** [comment]
Any progress on this? Would be very helpful!

**Comment by charleswg** [comment]
Please share the sample script for simulated survival data (linear and nonlinear) as used in the paper.

**Comment by jaredleekatzman** [comment]
I've uploaded the code and Dockerfiles for experiments from the paper. Let me know if there is any trouble running them
