### ISSUE TITLE
Negative log likelihood equation

### ISSUE THREAD

**Issue by jmigual** [jaredleekatzman/DeepSurv#40]
Hello,

I've read your paper and when looking for the negative log likelihood equation and implementation it looks like they are not the same. In the paper there's equation 3 which is like this:

<img src=https://user-images.githubusercontent.com/6493651/37540797-acdbbc7e-292e-11e8-9f21-d102dd559125.png width=400>

But looking at the code it seems that you are not using the risk set (R(t)) and it behaves like this (notice the absence of R(Ti) in the second summation):

<img src=https://user-images.githubusercontent.com/6493651/37540986-57c77ae2-292f-11e8-80e5-6c586c94642e.png width=370>

Is there a reason for this?

**Comment by jaredleekatzman** [comment]
Hi Joan,

Thank you checking the code. The code should be calculating the correct negative log likelihood (the first equation). 
The training data is preprocessed to be sorted in reverse order of death (line 328 <https://github.com/jaredleekatzman/DeepSurv/blob/master/deepsurv/deep_surv.py#L328>). Therefore, when you look at line 164 <https://github.com/jaredleekatzman/DeepSurv/blob/master/deepsurv/deep_surv.py#L164>, when we are taking the cumulative sum down the matrix, it is accumulating the sum of the e^h(x) for each individual’s risk set. 

Le me know if you have any more questions!

Jared

**Comment by gunpowdergreentea** [comment]
why is the reasoning to go in reverse order of death?

**Comment by SZH1230456** [comment]
emm...I'm also confused about the equation above. How did you get the set of R{Ti}? And what' s the meaning of risk.T in line 165?
![image](https://user-images.githubusercontent.com/38172534/67206009-6cfcbe00-f443-11e9-9b9f-0786baa89698.png)
