### ISSUE TITLE
No module named 'deep_surv'

### ISSUE THREAD

**Issue by MohdSafwanAhmad** [jaredleekatzman/DeepSurv#48]
As I try to run DeepSurv Example.ipynb, I get the following error:

Traceback (most recent call last):
  File "D:\Thesis\DeepSurv\deepsurv_eg.py", line 4, in <module>
    import deep_surv
ModuleNotFoundError: No module named 'deep_surv'
[Finished in 0.1s with exit code 1]

I have the updated versions of Theano and Lasagne installed.

**Comment by Huaichao2018** [comment]
i also have this issue, do you have solve it.

**Comment by AtzeniMichele** [comment]
I have the same issue, how did you solve it?
