### ISSUE TITLE
error when using get_concordance_index()

### ISSUE THREAD

**Issue by abracadabrac** [jaredleekatzman/DeepSurv#6]
Hello and thank you for sharing your great work. 

I have trained a network :

`network = deepsurv.DeepSurv(10,0.0001)
log = network.train(d_train, d_valid, n_epochs=500)`

`[INFO] Training CoxMLP
Finished Training with 500 iterations in 20.05s`

It seems it was able to predict a risk vector : 

`network.predict_risk(d_valid['x'])`

`array([[ -5.24271558e+00],
       [ -1.13109659e+03],
       [  4.15896825e+00],
       [ -7.84299117e+00],
       [  1.62468140e+01],
       [ -3.04364481e+00],
       [ -3.50972074e+00],
       [ -2.26831663e+02],
       [ -3.07352921e+00],
       [ -1.57916871e+00],
.....`

but when using get_concordance_index() like this :

`network.get_concordance_index(d_test['x'],d_test['t'],d_test['e'])`

I get this error :

`---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-81-6429d32df4a4> in <module>()
----> 1 network.get_concordance_index(d_test['x'],d_test['t'],d_test['e'])

/Library/anaconda/lib/python3.5/site-packages/deepsurv/deep_surv.py in get_concordance_index(self, x, t, e, **kwargs)
    268         return concordance_index(t,
    269             partial_hazards,
--> 270             e)
    271 
    272     def train(self,

/Library/anaconda/lib/python3.5/site-packages/lifelines/utils/__init__.py in concordance_index(event_times, predicted_event_times, event_observed)
    384     return _concordance_index(event_times,
    385                               predicted_event_times,
--> 386                               event_observed)
    387 
    388 

/Library/anaconda/lib/python3.5/site-packages/lifelines/utils/__init__.py in _concordance_index(event_times, predicted_event_times, event_observed)
    857             died_ix = next_ix
    858         else:
--> 859             assert not (has_more_died or has_more_censored)
    860             break
    861 

AssertionError:`

Have you any idea of how I could fix it ? 

Thank you !

**Comment by jaredleekatzman** [comment]
DeepSurv relies on the [lifelines](https://github.com/CamDavidsonPilon/lifelines) package to calculate the concordance index. It looks based on the characteristics of your dataset, lifelines cannot calculate the concordance index.

I recommend looking at how at the number of censored examples and making sure it is valid under the assumptions lifelines make (which you can find how they calculate concordance index [here](https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/utils/__init__.py)

**Comment by abracadabrac** [comment]
Thank you very much !

**Comment by zhxiaokang** [comment]
> DeepSurv relies on the [lifelines](https://github.com/CamDavidsonPilon/lifelines) package to calculate the concordance index. It looks based on the characteristics of your dataset, lifelines cannot calculate the concordance index.
> 
> I recommend looking at how at the number of censored examples and making sure it is valid under the assumptions lifelines make (which you can find how they calculate concordance index [here](https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/utils/__init__.py)

Hi @jaredleekatzman  I compared what I got from `DeepSurv`'s `get_concordance_index` and `lifelines`'s `concordance_index`, but the former one gave me strange result.

My toy data is as follows:
```
train_data['t']
# -> [1506.,  765.,  308., 1147.,  180.]
train_data['e']
# -> [1, 1, 0, 0, 1]
pred = model.predict_risk(train_data['x'])
# -> [3578.27762551, 3488.10561024, 3816.7970456 , 2686.47916451, 5851.97509535]
```
(`model` is the trained model by `deepsurv`)

If I use `lifelines` to calculate the CI:
```
from lifelines.utils import concordance_index as ci_lifelines
ci_lifelines(train_data['t'], -pred, train_data['e'])
# -> 0.8333333333333334
```
It seems reasonable to me since the prediction is quite OK. But if I use 'DeepSurv' instead:
```
model.get_concordance_index(train_data['x'], train_data['t'], train_data['e'])
# -> 0.5
```
As said [here](https://github.com/jaredleekatzman/DeepSurv/blob/41eed003e5b892c81e7855e400861fa7a2d9da4f/deepsurv/deep_surv.py#L295), 0.5 means "random predictions".
